local malas_ngodonf = require("malas-ngodonf.init")
describe("Default options", function()
  malas_ngodonf.setup({})
  it("can say hello", function()
    assert.are.equal("Hello John Doe", malas_ngodonf.hello())
  end)
  it("can say bye", function()
    assert.are.equal("Bye John Doe", malas_ngodonf.bye())
  end)
end)

describe("User defined options", function()
  malas_ngodonf.setup({ name = "John Smith" })
  it("can say hello", function()
    assert.are.equal("Hello John Smith", malas_ngodonf.hello())
  end)
  it("can say bye", function()
    assert.are.equal("Bye John Smith", malas_ngodonf.bye())
  end)
end)
